### ISSUE TITLE
Need information about ID3 parser for MPEG2-TS file

### ISSUE THREAD

**Issue by sunildeshpande** [larsbs/id3v2lib#1]
Hi,

I found your software for ID3 extraction. This is working very good and I am able to understand some thing for that. It is a amazing work.

https://github.com/larsbs/id3v2lib
I have one question for you, did you try to support ID3 parsing for MPEG2-TS streams (from HLS)? I am looking for that code base which parses the ID3 tags from the MPEG2-TS streams (from HLS).
Could you please guide me ?
Warm Regards,

Sunil Deshpande
Bangalore

**Comment by bumblebritches57** [comment]
I'm actually working on an MPEG2 Transport/Program Stream de/muxing library, what exactly do you need?
