### ISSUE TITLE
i dont know, how i build the dll

### ISSUE THREAD

**Issue by Ollowain87** [larsbs/id3v2lib#17]
Hallo,

i dont know what i should do. I dont understand the instructions in the read me. Do you have an Video tutorial?

Building using Microsoft Visual Studio
Microsoft Visual Studio needs a slightly different way of building. Open the Visual Studio Developers Console, ch into the id3v2lib folder and execute the following:

$ mkdir build && cd build
$ cmake ..

This should leave you with several MSVS projects in the \build directory. Open ALL_BUILD.vcxproj with Visual Studio and build it as usual. The resulting lib file can be found in \build\src\Debug\id3v2.lib

**Comment by larsbs** [comment]
I've never build the library using visual studio. This feature was added by a third party so it's not fully supported. But, what have you tried?

**Comment by Ollowain87** [comment]
**first i go in this folder**
<img width="874" alt="unbenannt" src="https://cloud.githubusercontent.com/assets/20914997/20248477/42922cbe-a9e5-11e6-8bd5-88ff8f94e353.PNG">
**Then I  open the Visual Studio Developers Console, an execute 
$ mkdir build && cd build**

<img width="769" alt="unbenannt2" src="https://cloud.githubusercontent.com/assets/20914997/20248490/6dacbedc-a9e5-11e6-87ea-7c82cbe9e7f5.PNG">

**Then I get this**
<img width="501" alt="unbenannt3" src="https://cloud.githubusercontent.com/assets/20914997/20248502/b2b54490-a9e5-11e6-8d5d-dd4faef2776f.PNG">

**Then I execute cmake .. and I get this**
<img width="498" alt="3" src="https://cloud.githubusercontent.com/assets/20914997/20248513/f2f58af6-a9e5-11e6-9229-e35400daeb26.PNG">
The console says everytime 
The command "cmake" is either misspelled, or could not be found."

**Then I got to the subfolder**
<img width="575" alt="5" src="https://cloud.githubusercontent.com/assets/20914997/20248522/367ec08a-a9e6-11e6-9e09-c35d7100e68d.PNG">

**Then I  open the Visual Studio Developers Console, an execute 
$ mkdir build && cd build**

<img width="581" alt="7" src="https://cloud.githubusercontent.com/assets/20914997/20248529/4dd7a53a-a9e6-11e6-98cd-2c9d8fdb70cf.PNG">

**Then I execute cmake .. and I get this**
<img width="545" alt="8" src="https://cloud.githubusercontent.com/assets/20914997/20248531/69eba596-a9e6-11e6-8904-cabe44b11ca7.PNG">
The console says everytime 
The command "cmake" is either misspelled, or could not be found."


**Then I go a Folder up and I execute cmake .. and I get this  **
<img width="527" alt="9" src="https://cloud.githubusercontent.com/assets/20914997/20248546/ae2d0c68-a9e6-11e6-802d-85d2c56d998f.PNG">
The console says everytime 
The command "cmake" is either misspelled, or could not be found."

**Comment by larsbs** [comment]
Well, apparently you are missing cmake on your machine: https://cmake.org/. Did you install it?

**Comment by Ollowain87** [comment]
yes, it is install 
![image](https://cloud.githubusercontent.com/assets/20914997/20276407/6631b4a2-aa9c-11e6-9f73-13631a1a0424.png)

**Comment by larsbs** [comment]
Well it's not on your path variable then, because cmd is not finding it.

http://tulip.labri.fr/TulipDrupal/?q=node/1081

Or you can add it manually if you know where your cmake installation is located.

**Comment by Ollowain87** [comment]
Hallo,

it has work with cmake. When I build the Project I get many Errors. 
1>------ Start creating: Projekt: ZERO_CHECK, Konfiguration: Debug Win32 ------
1>  Checking Build System
1>  CMake does not need to re-run because C:/Users/Nico/Downloads/id3v2lib-master/id3v2lib-master/build/CMakeFiles/generate.stamp is up-to-date.
1>  CMake does not need to re-run because C:/Users/Nico/Downloads/id3v2lib-master/id3v2lib-master/build/src/CMakeFiles/generate.stamp is up-to-date.
2>------ Start creating: Projekt: id3v2, Konfiguration: Debug Win32 ------
2>  Building Custom Rule C:/Users/Nico/Downloads/id3v2lib-master/id3v2lib-master/src/CMakeLists.txt
2>  CMake does not need to re-run because C:\Users\Nico\Downloads\id3v2lib-master\id3v2lib-master\build\src\CMakeFiles\generate.stamp is up-to-date.
2>cl : Command line warning D9002: unknow Option "-std=c99" is ignored.
2>cl : Command line warning D9002: unknow Option "-fPIC" is ignored.
2>  frame.c
2>  header.c
2>C:\Users\Nico\Downloads\id3v2lib-master\id3v2lib-master\src\header.c(40): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
2>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\ucrt\stdio.h(205): note: Siehe Deklaration von "fopen"
2>C:\Users\Nico\Downloads\id3v2lib-master\id3v2lib-master\src\header.c(71): warning C4554: "&": Check operator precedence for possible error; use parentheses to clarify precedence2>  id3v2lib.c
2>C:\Users\Nico\Downloads\id3v2lib-master\id3v2lib-master\src\id3v2lib.c(33): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
2>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\ucrt\stdio.h(205): note: Siehe Deklaration von "fopen"
2>C:\Users\Nico\Downloads\id3v2lib-master\id3v2lib-master\src\id3v2lib.c(125): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
2>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\ucrt\stdio.h(205): note: Siehe Deklaration von "fopen"
2>C:\Users\Nico\Downloads\id3v2lib-master\id3v2lib-master\src\id3v2lib.c(126): warning C4996: 'tmpfile': This function or variable may be unsafe. Consider using tmpfile_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
2>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\ucrt\stdio.h(431): note: see deklartioen from "tmpfile"
2>C:\Users\Nico\Downloads\id3v2lib-master\id3v2lib-master\src\id3v2lib.c(212): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
2>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\ucrt\stdio.h(205): note: see Deklartionen from "fopen"
2>C:\Users\Nico\Downloads\id3v2lib-master\id3v2lib-master\src\id3v2lib.c(213): warning C4996: 'tmpfile': This function or variable may be unsafe. Consider using tmpfile_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
2>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\ucrt\stdio.h(431): note: see Deklartionen from "tmpfile"
2>C:\Users\Nico\Downloads\id3v2lib-master\id3v2lib-master\src\id3v2lib.c(376): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
2>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\ucrt\stdio.h(1769): note:see Deklartionen from "sprintf"
2>C:\Users\Nico\Downloads\id3v2lib-master\id3v2lib-master\src\id3v2lib.c(392): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
2>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\ucrt\stdio.h(1769): note: see Deklartionen from "sprintf"
2>C:\Users\Nico\Downloads\id3v2lib-master\id3v2lib-master\src\id3v2lib.c(410): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
2>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\ucrt\stdio.h(1769): note: see Deklartionen from "sprintf"
2>C:\Users\Nico\Downloads\id3v2lib-master\id3v2lib-master\src\id3v2lib.c(539): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
2>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\ucrt\stdio.h(205): note: see Deklartionen from "fopen"
2>  types.c
2>  utils.c
2>C:\Users\Nico\Downloads\id3v2lib-master\id3v2lib-master\src\utils.c(183): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
2>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\ucrt\string.h(335): note: see Deklartionen from "strncpy"
2> Code is generated...
2>  id3v2.vcxproj -> C:\Users\Nico\Downloads\id3v2lib-master\id3v2lib-master\build\src\Debug\id3v2.lib
3>------ Erstellen gestartet: Projekt: ALL_BUILD, Konfiguration: Debug Win32 ------
3>  Building Custom Rule C:/Users/Nico/Downloads/id3v2lib-master/id3v2lib-master/CMakeLists.txt
3>  CMake does not need to re-run because C:\Users\Nico\Downloads\id3v2lib-master\id3v2lib-master\build\CMakeFiles\generate.stamp is up-to-date.
4>------ Create skipped: Projekt: INSTALL, Konfiguration: Debug Win32 ------
4>No project to be created was selected for this solution configuration.
========== created: 3 succesful, 0 faulty, 0 currently,. 1 skipped==========

When I will Include the lib to my Project, I get this message
![image](https://cloud.githubusercontent.com/assets/20914997/20326717/31512832-ab8a-11e6-8181-b485a67f9100.png)

In english
There was no reference to "xxxxxxxx" be added. Make sure that accessing that file can be and is it a valid assembly or com component

**Comment by Ollowain87** [comment]
Hallo,

have nothing an idea, what the Problem ist?

**Comment by sbusch42** [comment]
Actually, it seems the library has been built successfully. According to your logs, it is located in "C:\Users\Nico\Downloads\id3v2lib-master\id3v2lib-master\build\src\Debug\id3v2.lib". However in your project you try to read it from the wrong path. Enter the correct path to link against the library, everything else seems to work fine at this point.

**Comment by larsbs** [comment]
Closing. Thanks @sbusch42 for taking your time to answer.

**Comment by miguelestradam36** [comment]
Can somebody help me with this ? 
I am currently using the library, I already installed everything, nevertheless Visual Studio 2019 still tells that there is some mistake with the library. 
![image](https://user-images.githubusercontent.com/60716985/98487559-3da12680-21e9-11eb-99e7-081a15fd845b.png)
