### ISSUE TITLE
EXC_BAD_ACCESS Error

### ISSUE THREAD

**Issue by sxgfxm** [larsbs/id3v2lib#21]
hi, 
    Thanks a lot for id3v2lib which helps me insert ID3v2 Tag to mp3 files with no metadata before.
But sometimes I got this error "malloc: *** error for object 0x172834d40: Invalid pointer dequeued from free list" and I can't find out what's wrong. Is there any advice ?

**Comment by Gray-Wind** [comment]
@sxgfxm Hello, how did you solve your issue?
